// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2xpwPgeMpr4qIwB1dDoisOQbDlfkO6eU',
    appId: '1:475873591921:web:96b96a62ed9799548d91d0',
    messagingSenderId: '475873591921',
    projectId: 'spotigen-b2954',
    authDomain: 'spotigen-b2954.firebaseapp.com',
    storageBucket: 'spotigen-b2954.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLiIk3tSHV7NnRLBgjykaZ_pl2PIF8ZBQ',
    appId: '1:475873591921:android:cc471f99a99c839b8d91d0',
    messagingSenderId: '475873591921',
    projectId: 'spotigen-b2954',
    storageBucket: 'spotigen-b2954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiB_ecIuQV84n32iazqnKE812zcdHnv1w',
    appId: '1:475873591921:ios:b89551f785040a5f8d91d0',
    messagingSenderId: '475873591921',
    projectId: 'spotigen-b2954',
    storageBucket: 'spotigen-b2954.appspot.com',
    iosClientId: '475873591921-rklbvspkmrihconfngrhpvogphoai6h9.apps.googleusercontent.com',
    iosBundleId: 'com.licenta.playlistGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiB_ecIuQV84n32iazqnKE812zcdHnv1w',
    appId: '1:475873591921:ios:b89551f785040a5f8d91d0',
    messagingSenderId: '475873591921',
    projectId: 'spotigen-b2954',
    storageBucket: 'spotigen-b2954.appspot.com',
    iosClientId: '475873591921-rklbvspkmrihconfngrhpvogphoai6h9.apps.googleusercontent.com',
    iosBundleId: 'com.licenta.playlistGenerator',
  );
}
