name: playlist_generator
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  lottie: ^1.2.1
  http: ^0.13.6
  flutter_inappwebview: ^5.7.2+3
  shared_preferences: ^2.1.1
  syncfusion_flutter_charts: ^19.1.54
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  url_launcher: ^6.1.11
  audioplayers: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - lib/assets/images/
    # - lib/assets/images/album_posters
    - lib/assets/81966-girl-listening-to-music.json
    - assets/
